'''A module for helpers, as to not clutter others.

This directory can be used to store helper functions that are used
in feature module backend or other scenarios where code legibility
is suffering.

Warning:
    DO NOT EDIT THIS FILE! This file is a temporary placeholder for
    real helper functions. If you wish to add a helper function, please
    create a new file with a sensible name in this directory.
'''

def pointless_function():
    '''A function that does nothing.

    Returns:
        str: A string that says nothing.
    '''
    return "You have successfully called a function that does nothing. Congratulations!"